### ISSUE TITLE
Configure Travis

### ISSUE THREAD

**Issue by bcroden** [bcroden/QuizDeck-Server#17]
Here is the bare bones .travis.yml needed to build a java app on travis:

```
language: java
jdk:
  - oraclejdk8
before_install:
 - chmod +x gradlew
```

The chmod is important as the windows-generated wrapper is not executable by default on linux.

**Comment by bcroden** [comment]
To get travis to deploy to heroku you need to download the travis and heroku cli's and set up the .travis.yml file with an encrypted api key.
- Download Ruby: http://rubyinstaller.org/downloads/archives
  - I've had problems with some command line tools using ruby 2.x, I don't remember if it was these or not, but you should probably use 1.x just to be safe.
- Download Heroku CLI: https://toolbelt.heroku.com/
- Login to Heroku with the cli
- Install Travis CLI
  - run `$ gem install travis -v 1.8.2 --no-rdoc --no-ri`
- Update the .travis.yml with the secret api key.
  - run `$ travis setup heroku`
- Make travis only deploy on master branch
  - Make the .travis.yml look like this:
  
  ```
  deploy:
    provider: heroku
    api_key:
      secure: ...long cyphertext...
    app: <name of the app on heroku>
    on:
      branch: master
      repo: <github-username>/<github-repo>
  ```
